theme: jekyll-theme-minimal

title: Ismael Mendoza's Website
description: Hi, I'm Ismael! I'm a fifth-year Physics PhD student at the University of Michigan, advised by Camille Avestruz. I completed my BS in Physics (2018) and MS in Computer Science (2019) at Stanford University, where I was advised by Patricia Burchat. My research focuses in developing novel machine learning techniques to solve problems in cosmology. I am also an active full member and sprint coordinator for the LSST Dark Energy Science Collaboration (DESC).
